THEME = {
    "meta": {"name": "Frutiger Aero", "author": "FurizAlex"},
	"background_image":  "assets/background/frutiger_aero.jpg",
    "defaults":          {"fg": "white",   "bg": "black"},
    "text":              {"fg": "white",   "bg": "black"},
    "keyword":           {"fg": "aqua",  "bg": "black", "bold": True},
    "string":            {"fg": "cyan",    "bg": "black"},
    "comment":           {"fg": "white",   "bg": "black", "dim": True},
    "number":            {"fg": "aero",  "bg": "black"},
    "diagnosticError":   {"fg": "red",     "bg": "black"},
    "selection":         {"fg": "aero",   "bg": "white"},
    "lineNumber":        {"fg": "black",   "bg": "black"},
    "currentLineNumber": {"fg": "aero",  "bg": "blue", "bold": True},
    "statusBar":         {"fg": "white",   "bg": "aero"},
    "tab":               {"fg": "white",   "bg": "black"},
    "activeTab":         {"fg": "aero",   "bg": "white", "bold": True},
    "explorerTitle":     {"fg": "aero",  "bg": "aero", "bold": True},
    "explorerItem":      {"fg": "white",   "bg": "aero"},
    "explorerSelection": {"fg": "aero",   "bg": "white"},
    "paletteBorder":     {"fg": "white",   "bg": "aero"},
    "paletteTitle":      {"fg": "white",  "bg": "aero", "bold": True},
    "paletteItem":       {"fg": "white",   "bg": "aero"},
    "paletteSelection":  {"fg": "aero",   "bg": "white"},
    "searchBar":         {"fg": "black",   "bg": "white"},
    "splitter":          {"fg": "white",   "bg": "black"},
    "activeSplitter":    {"fg": "aero",  "bg": "black"},
	"language_overrides": {
    "python": {"cursor": "yellow"},
    "markdown": {"cursor": "white", "selection": "grey"},
	},
}