THEME = {
    "meta": {"name": "Globe", "author": "FurizAlex"},
	"background_image":  "assets/background/earth_image_from_nasa.jpg",
    "defaults":          {"fg": "grey",   "bg": "black"},
    "text":              {"fg": "grey",   "bg": "black"},
    "keyword":           {"fg": "aqua",  "bg": "black", "bold": True},
    "string":            {"fg": "cyan",    "bg": "black"},
    "comment":           {"fg": "grey",   "bg": "black", "dim": True},
    "number":            {"fg": "blue",  "bg": "black"},
    "diagnosticError":   {"fg": "grey",     "bg": "black"},
    "selection":         {"fg": "blue",   "bg": "grey"},
    "lineNumber":        {"fg": "grey",   "bg": "dark grey", "dim": True},
    "currentLineNumber": {"fg": "blue",  "bg": "black", "bold": True},
    "statusBar":         {"fg": "grey",   "bg": "black"},
    "tab":               {"fg": "grey",   "bg": "black"},
    "activeTab":         {"fg": "black",   "bg": "grey", "bold": True},
    "explorerTitle":     {"fg": "blue",  "bg": "black", "bold": True},
    "explorerItem":      {"fg": "grey",   "bg": "black"},
    "explorerSelection": {"fg": "black",   "bg": "grey"},
    "paletteBorder":     {"fg": "grey",   "bg": "black"},
    "paletteTitle":      {"fg": "grey",  "bg": "black", "bold": True},
    "paletteItem":       {"fg": "grey",   "bg": "black"},
    "paletteSelection":  {"fg": "black",   "bg": "grey"},
    "searchBar":         {"fg": "black",   "bg": "grey"},
    "splitter":          {"fg": "grey",   "bg": "black"},
    "activeSplitter":    {"fg": "blue",  "bg": "black"},
	"language_overrides": {
    "python": {"cursor": "yellow"},
    "markdown": {"cursor": "black", "selection": "grey"},
	},
}