THEME = {
    "meta":              {"name": "Iridescent", "author": "FurizAlex"},
    "dither":            True,
    "gradient": [
        (0.0,  "#6D1A1A"),
        (0.2,  "#6F7513"),
        (0.4,  "#106E12"),
        (0.6,  "#143466"),
        (0.8,  "#241661"),
        (1.0,  "#772177"),
    ],
    "defaults":          {"fg": "white",     "bg": "black"},
    "text":              {"fg": "white",     "bg": "black"},
    "keyword":           {"fg": "yellow",  "bg": "black", "bold": True},
    "string":            {"fg": "white",     "bg": "black"},
    "comment":           {"fg": "grey",     "bg": "black", "dim": True},
    "number":            {"fg": "aqua",  "bg": "black"},
    "diagnosticError":   {"fg": "red",      "bg": "black"},
    "selection":         {"fg": "magenta",    "bg": "white"},
    "lineNumber":        {"fg": "aqua",     "bg": "black", "dim": True},
    "currentLineNumber": {"fg": "white",     "bg": "black", "bold": True},
    "statusBar":         {"fg": "white",    "bg": "black"},
    "tab":               {"fg": "grey",     "bg": "black"},
    "activeTab":         {"fg": "white",     "bg": "black",  "bold": True},
    "explorerTitle":     {"fg": "white",  "bg": "black",  "bold": True},
    "explorerItem":      {"fg": "white",     "bg": "black"},
    "explorerSelection": {"fg": "black",    "bg": "white"},
    "paletteBorder":     {"fg": "white",     "bg": "black"},
    "paletteTitle":      {"fg": "white",  "bg": "black",  "bold": True},
    "paletteItem":       {"fg": "white",     "bg": "black"},
    "paletteSelection":  {"fg": "black",    "bg": "magenta"},
    "searchBar":         {"fg": "black",    "bg": "white"},
    "splitter":          {"fg": "white",     "bg": "black",  "dim": True},
    "activeSplitter":    {"fg": "white",  "bg": "black"},
}