THEME = {
    "meta": {"name": "Amiga", "author": "FurizAlex"},
    "defaults":          {"fg": "white",   "bg": "black"},
    "text":              {"fg": "white",   "bg": "black"},
    "keyword":           {"fg": "yellow",  "bg": "black", "bold": True},
    "string":            {"fg": "cyan",    "bg": "black"},
    "comment":           {"fg": "white",   "bg": "black", "dim": True},
    "number":            {"fg": "yellow",  "bg": "black"},
    "diagnosticError":   {"fg": "red",     "bg": "black"},
    "selection":         {"fg": "yellow",   "bg": "white"},
    "lineNumber":        {"fg": "white",   "bg": "black", "dim": True},
    "currentLineNumber": {"fg": "yellow",  "bg": "black", "bold": True},
    "statusBar":         {"fg": "white",   "bg": "black"},
    "tab":               {"fg": "white",   "bg": "black"},
    "activeTab":         {"fg": "black",   "bg": "white", "bold": True},
    "explorerTitle":     {"fg": "yellow",  "bg": "black", "bold": True},
    "explorerItem":      {"fg": "white",   "bg": "black"},
    "explorerSelection": {"fg": "black",   "bg": "yellow"},
    "paletteBorder":     {"fg": "white",   "bg": "black"},
    "paletteTitle":      {"fg": "yellow",  "bg": "black", "bold": True},
    "paletteItem":       {"fg": "white",   "bg": "black"},
    "paletteSelection":  {"fg": "black",   "bg": "white"},
    "searchBar":         {"fg": "black",   "bg": "white"},
    "splitter":          {"fg": "white",   "bg": "black"},
    "activeSplitter":    {"fg": "yellow",  "bg": "black"},
}